steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/testmlops-446623/advertising_roi_model', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/testmlops-446623/advertising_roi_model']

- name: 'gcr.io/testmlops-446623/advertising_roi_model'
  entrypoint: 'bash'
  args:
   - '-c'
   - |
      python -m pytest

- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/NancySaxena1-eng/CI-AdCampaign-model-training.git']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'CI-AdCampaign-model-training/advertising_model_training.py', 'gs://us-central1-mlops-airflow-bfa9c57d-bucket/dags']

images:
- 'gcr.io/testmlops-446623/advertising_roi'

options:
  logging: CLOUD_LOGGING_ONLY
